### ISSUE TITLE
не работает 

### ISSUE THREAD

**Issue by playlogitech** [wcde/custom-hires-fix-for-automatic1111#2]
последний коммит каломатика1111

Error running postprocess: C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py", line 152, in postprocess
    return custom_processing.upscale(p, processed, self.config)
AttributeError: module 'custom_processing' has no attribute 'upscale'

**Comment by wcde** [comment]
Могу предположить что обновление через вкладку экстеншенов сломано и файл custom_processing.py не обновился. Чистая установка экстеншена работает.

**Comment by playlogitech** [comment]
лево руля, снес конфиг, перезапустил, начало работать
возможно еще стоит указать, что вот эти крутилки должны быть кратны 64
![image](https://user-images.githubusercontent.com/121442734/229507119-c049f140-aefc-4f71-a631-b2c52ad56169.png)

иначе выбивает ошибку в консоль

```
Error running postprocess: C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py", line 152, in postprocess
    return custom_processing.upscale(p, processed, self.config)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\custom_processing.py", line 109, in upscale
    samples = sampler.sample_img2img(p, samples.to(devices.dtype), noise, cond, uncond, steps=steps,
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\custom_processing.py", line 31, in sampler_dpmu
    denoised = x if i == 0 else model(x, sigmas[i] * s_in, **extra_args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\patch.py", line 71, in forward
    return super().forward(*args, **kwdargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\patch.py", line 35, in _forward
    m, u = merge.bipartite_soft_matching_random2d(x, w, h, sx, sy, r, no_rand)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\merge.py", line 43, in bipartite_soft_matching_random2d
    idx_buffer = idx_buffer.view(1, hsy, wsx, sy, sx, 1).transpose(2, 3).reshape(1, N, 1)
RuntimeError: shape '[1, 18537, 1]' is invalid for input of size 18260
```

**Comment by playlogitech** [comment]
> Это: https://github.com/SLAPaper/a1111-sd-webui-tome Плюс это из pip: https://pypi.org/project/tomesd/ И не будет проблем.

окей, я эту ставил несколько дней назад https://git.mmaker.moe/mmaker/sd-webui-tome

**Comment by playlogitech** [comment]
С другим ToMe ничего не изменилось.

`Error running postprocess: C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py", line 152, in postprocess
    return custom_processing.upscale(p, processed, self.config)
  File "C:\stable-diffusion-webui\extensions\custom-hires-fix-for-automatic1111\custom_processing.py", line 109, in upscale
    samples = sampler.sample_img2img(p, samples.to(devices.dtype), noise, cond, uncond, steps=steps,
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\patch.py", line 71, in forward
    return super().forward(*args, **kwdargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\patch.py", line 35, in _forward
    m, u = merge.bipartite_soft_matching_random2d(x, w, h, sx, sy, r, no_rand)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\tomesd\merge.py", line 43, in bipartite_soft_matching_random2d
    idx_buffer = idx_buffer.view(1, hsy, wsx, sy, sx, 1).transpose(2, 3).reshape(1, N, 1)
RuntimeError: shape '[1, 18426, 1]' is invalid for input of size 18260`

`cute 1girl, blush, smile, purple bob cut, wavy hair, blue eyes, green one-piece swimsuit, spandex, detailed texture, cinematic lighting, high quality
Negative prompt: bad anatomy, EasyNegative, (low quality:1.5), particles, blurred, banding, multicolored hair, navel, covered nipples, cameltoe
Steps: 25, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3825072584, Size: 512x768, Model hash: 31e00b76e9, Model: WaifuReaper_v2, Denoising strength: 0.63, Hires upscale: 2, Hires steps: 20, Hires upscaler: Latent (nearest-exact), AddNet Enabled: True, AddNet Module 1: LoRA, AddNet Model 1: clothingKyosui_v10(d23e326de1d1), AddNet Weight A 1: 0.5, AddNet Weight B 1: 0.5, AddNet Module 2: LoRA, AddNet Model 2: shinkaiDiffusion_yourNameLORA(6cb3dc1de279), AddNet Weight A 2: 0.45, AddNet Weight B 2: 0.45, AddNet Module 3: LoRA, AddNet Model 3: himitsu-styled-e10_32_8_768_768_anyV3(6fd76ed06f14), AddNet Weight A 3: 0.5, AddNet Weight B 3: 0.5`

![image](https://user-images.githubusercontent.com/121442734/229512187-52099cec-a5d2-468b-804a-9c444bd245ec.png)
![image](https://user-images.githubusercontent.com/121442734/229512251-b07055d4-dfcf-4bf4-9c18-d83787833a2b.png)
![image](https://user-images.githubusercontent.com/121442734/229512296-9548a674-9ad9-493b-9af3-adbf5c7a88c9.png)

**Comment by wcde** [comment]
> Внутренний апскейлинг и потом ресайз в то разрешение, в котором генерировалась пикча?

Если коротко - последовательный апскейл двумя апскейлерами. Если использовать один проход, то при апскейле в 2 и более раз вылезает много проблем при агрессивной генерации мелких деталей, потери в скорости не сильно критичные - в пределах 20-30% на промежуточный апскейл.

> С другим ToMe ничего не изменилось.

Вместо старого пакета точно новый из pip стоит? В новом на 35 строчке в tomesd\patch.py нет такого кода.
