### ISSUE TITLE
RuntimeError: The size of tensor a (112) must match the size of tensor b (120) at non-singleton dimension 3

### ISSUE THREAD

**Issue by AndreyRGW** [wcde/custom-hires-fix-for-automatic1111#6]
```
13:44:47-040787 ERROR    Running script postprocess image:
                         F:\WBC\automatic\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py:
                         RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\WBC\automatic\modules\scripts.py:466 in postprocess_image                                                         │
│                                                                                                                      │
│   465 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 466 │   │   │   │   script.postprocess_image(p, pp, *args)                                                         │
│   467 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ F:\WBC\automatic\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py:180 in postprocess_image  │
│                                                                                                                      │
│   179 │   │   │   shared.state.nextjob()                                                                             │
│ ❱ 180 │   │   │   x = self.gen(pp.image)                                                                             │
│   181 │   │   │   shared.state.nextjob()                                                                             │
│                                                                                                                      │
│ F:\WBC\automatic\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py:242 in gen                │
│                                                                                                                      │
│   241 │   │   if x_big is not None and self.config.first_latent != 1:                                                │
│ ❱ 242 │   │   │   sample = (sample * (1 - self.config.first_latent)) + (x_big * self.config.fi                       │
│   243 │   │   image_conditioning = self.p.img2img_image_conditioning(decoded_sample, sample)                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (112) must match the size of tensor b (120) at non-singleton dimension 3
```

**Comment by Jenetrix** [comment]
Same issue on 1.6.0. Seems to have something to do with the resolution of the base image being rounded inconsistently when scaled. Happened when i tried to use a base image resolution that when scaled at that aspect ratio needed rounding due to decimals.

```
*** Error running postprocess_image: F:\Stable Diffusion\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py
    Traceback (most recent call last):
      File "F:\Stable Diffusion\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\Stable Diffusion\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py", line 188, in postprocess_image
        x = self.filter(x)
      File "F:\Stable Diffusion\extensions\custom-hires-fix-for-automatic1111\scripts\custom_hires_fix.py", line 346, in filter
        samples = self.sampler.sample_img2img(self.p, sample.to(devices.dtype), noise, self.cond, self.uncond,
      File "F:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\Stable Diffusion\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "F:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\Stable Diffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\Stable Diffusion\modules\sd_samplers_extra.py", line 70, in restart_sampler
        x = x + k_diffusion.sampling.torch.randn_like(x) * s_noise * (old_sigma ** 2 - last_sigma ** 2) ** 0.5
    RuntimeError: The size of tensor a (256) must match the size of tensor b (160) at non-singleton dimension 3

---
```
